// Generated by CoffeeScript 1.6.3
(function() {
  var mhacks;

  mhacks = new Firebase('https://mhacks.firebaseio.com/');

  $(function() {
    var cancel;
    cancel = function() {
      return $('.call-to-action').html("<a class='register' href='#'>Register</a>\n<span>- or -</span>\n<a class='sponsor' href='mailto:hackathon@umich.edu'>Sponsor</a>");
    };
    $('.call-to-action').delegate('#register-form', 'submit', function(e) {
      e.preventDefault();
      mhacks.push({
        email: $('.email').val()
      });
      $('.email').val('');
      return cancel();
    });
    $('.call-to-action').delegate('.cancel', 'click', cancel);
    return $('.call-to-action').delegate('.register', 'click', function(e) {
      console.log("clicked register");
      e.preventDefault();
      return $('.call-to-action').html("<form id='register-form' method='post' action='/register'>\n  <input class='email' type='email' placeholder='EMAIL' name='email' required>\n  <input type='submit' value='GO'>\n  <button type='button' class='cancel'>STOP</button>\n</form>");
    });
  });

}).call(this);
